name: View and Download Photo

on: push

jobs:
  run:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Code
        run: RUST_LOG=info ./unsplash-rs
